# Generated by Django 5.0.1 on 2024-01-11 13:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(default=""),
            preserve_default=False,
        ),
    ]
