# Generated by Django 5.0.1 on 2024-01-11 13:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_remove_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
